ASP_VARIABLE_VALUE_SYMBOL = 'variableValue'

ASP_ACTION_SYMBOL = 'action'
ASP_ACTION_PRECONDITION_SYMBOL = 'prec'

ASP_ACTION_EFFECT_SYMBOL = 'effect'

ASP_EFFECT_ADD_SYMBOL = 'add'
ASP_EFFECT_DELETE_SYMBOL = 'del'

ASP_TRUE_VALUE = 'trueValue'
ASP_FALSE_VALUE = 'falseValue'

ASP_GOAL_SYMBOL = 'goal'